#!/usr/bin/env bash

git clone --bare https://github.com/JBarlowDev/dotfiles.git
$HOME/.dotfiles

function dotfiles {
  git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

dotfiles checkout
dotfiles config --local status.showUntrackedFiles no
